## 1) Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when youmight choose one over the other.

ordinal encoding : ordinal encoding is encoding technique where the data is encoded in the ranking , the ranking is preserved ,each variable in the dataset is assigned to a numeric integer staring with 0 till n-1 variables , the ranking here is to be mentioned while creating instances of the OrdinalEndocer class

Label encoding : label encoding is a encoding techinque similar to the ordinal encoding but here the ranking is not preserved and it orders the ranking in the alphabeticall order 

when the ranking matters : like education of a person we can choose ordinal encoding 

when the ranking or order does not matter : geneder of a person then we can choose label encoding 

## 2) Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it ina machine learning project.

target guided ordinal encoding : this encoding technique is used when we create realtionship to the target variable

Target Guided Ordinal Encoding is a method of encoding categorical variables where the categories are ranked based on the target variable. This means that instead of arbitrarily assigning integer values to categories, each category is assigned a rank or score based on its relationship with the target variable. This can be particularly useful when there is a strong correlation between the categorical variable and the target variable.



In [4]:
import pandas as pd

data = {
    'School Location': ['Urban', 'Suburban', 'Rural', 'Urban', 'Suburban', 'Rural'],
    'Exam Score': [85, 90, 78, 79, 87, 82]
}
df = pd.DataFrame(data)

location_means = df.groupby('School Location')['Exam Score'].mean()

ordinal_mapping = location_means.to_dict()

df['School Location Encoded'] = df['School Location'].map(ordinal_mapping)




## 3) Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

## 4) For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.Show your code and explain the output.

data={
    'color
}

In [64]:
data={
    'color':['red','green','blue'],
    'size':['small','medium','large'],
    'material':['wood','metal','plastic']}

dataframe=pd.DataFrame(data)

dataframe.head()

# here for material column and color column we have applied one hot encoding technique
material_data=pd.get_dummies(dataframe['material'])
color_data=pd.get_dummies(dataframe['color'])

dataframe=pd.concat([dataframe,material_data])
dataframe=pd.concat([dataframe,color_data])

dataframe.fillna(0,inplace=True)

In [71]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

# Define the categories for Size
size_categories = [['small', 'medium', 'large']]
# Define the categories for Color and Material (since they are not predefined)
color_categories = [['red', 'green', 'blue']]
material_categories = [['wood', 'metal', 'plastic']]

# Initialize separate encoders for each categorical variable
size_encoder = OrdinalEncoder(categories=size_categories)
color_encoder = OrdinalEncoder(categories=color_categories)
material_encoder = OrdinalEncoder(categories=material_categories)

# Sample data
data = [['red', 'medium', 'wood'],
        ['green', 'small', 'metal'],
        ['blue', 'large', 'plastic']]

# Separate the features
colors = np.array(data)[:, 0].reshape(-1, 1)
sizes = np.array(data)[:, 1].reshape(-1, 1)
materials = np.array(data)[:, 2].reshape(-1, 1)

# Encode each feature separately
encoded_colors = color_encoder.fit_transform(colors)
encoded_sizes = size_encoder.fit_transform(sizes)
encoded_materials = material_encoder.fit_transform(materials)

# Concatenate the encoded features back together
encoded_data = np.concatenate((encoded_colors, encoded_sizes, encoded_materials), axis=1)

# Print the encoded data
print(encoded_data)


[[0. 1. 0.]
 [1. 0. 1.]
 [2. 2. 2.]]


## 5) Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Educationlevel. Interpret the results.

## 6) You are working on a machine learning project with a dataset containing several categoricalvariables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use foreach variable, and why?

for gender variable : we can perform label encoding 

for education level : here ranking matters to we use ordinal encoding 

for employemt status : we can use lable or onehot encoding  techinque . any of these two wont matter 

## 7) You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and twocategorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/East/West). Calculate the covariance between each pair of variables and interpret the results.