In [4]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a codeto print the data types of both the variables.

list_ contains the string object but 
array_list is a Numpy array haiving string object only

## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [13]:
print("datatype of list_ : ",type(list_[0]) )

print("datatype of array_list : " , type(array_list[0]))

datatype of list_ :  <class 'str'>
datatype of array_list :  <class 'numpy.str_'>


 ## Q3. Will there be any difference in the data type of the elements present in both the variables, list_ andarra_list? If so then print the data types of each and every element present in both the variables, list_and arra_list.

In [16]:
array_list = np.array(object = list_, dtype = int)

# the data type has been changed to integer

print(type(array_list[0]))

<class 'numpy.int32'>


## Q4. Write a code to find the following characteristics of variable, num_array: (i)	 shape (ii) size

In [21]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

print("shape : ",num_array.shape)
print("size : ",num_array.size)

shape :  (2, 3)
size :  6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy arraycreation function.

In [25]:
var =np.zeros((3,3),int)
print(var)
print(type(var))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


## Q6  Create an identity matrix of shape (5,5) using numpy functions?

In [26]:
var2=np.eye(5)
print(var2)
print(type(var2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>
